"""Asynchronous, GTK-free GStreamer recording backend.

The module exposes two layers.  :func:`build_recording_plan` produces an
inspectable immutable description without importing PyGObject, while
:class:`Recorder` owns the live GStreamer pipeline and its bus.  This split is
intentional: settings and pipeline policy can be tested offline, with no
microphone, display server or GTK main window.

Capture signals are generated by a second GStreamer pipeline.  The recording
pipeline is paused or has its ``valve`` closed while a signal is audible, so no
signal buffers are ever mixed into the encoded stream.  As with every recorder
using loudspeakers and a microphone in one room, hardware acoustic echo remains
a property of the selected devices; headphones avoid it completely.
"""

from __future__ import annotations

from array import array
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from enum import Enum, auto
import math
import os
from pathlib import Path
import stat
import sys
import time
from typing import Protocol

from .models import ChannelMode, RecordingFormat, RecordingSettings


class RecordingError(RuntimeError):
    """Base class for a recording operation that cannot be completed."""


class RecordingUnavailableError(RecordingError):
    """Raised when PyGObject, GStreamer or required plugins are unavailable."""


class PipelineBuildError(RecordingUnavailableError):
    """Raised when an element cannot be made, configured or linked."""


class RecordingPhase(Enum):
    """Lifecycle state of one :class:`Recorder`."""

    IDLE = auto()
    STARTING = auto()
    RECORDING = auto()
    PAUSING = auto()
    PAUSED = auto()
    RESUMING = auto()
    STOPPING = auto()
    STOPPED = auto()
    ERROR = auto()
    CLOSED = auto()


class RecordingEventType(Enum):
    """Events delivered by :class:`Recorder` on the GStreamer/GLib thread."""

    STATE_CHANGED = auto()
    SOURCE_FALLBACK = auto()
    CHANNEL_FALLBACK = auto()
    SIGNAL_ERROR = auto()
    FINALIZED = auto()
    ERROR = auto()


class RecordingSignal(Enum):
    """Distinct synthesized cues used for the four capture commands."""

    START = auto()
    PAUSE = auto()
    RESUME = auto()
    STOP = auto()


@dataclass(frozen=True, slots=True)
class RecordingSnapshot:
    """Immutable current state passed to presentation code."""

    phase: RecordingPhase
    output_path: Path | None
    elapsed_seconds: float
    requested_channels: int
    active_channels: int | None
    source_factory: str | None
    error: str | None = None


@dataclass(frozen=True, slots=True)
class RecordingEvent:
    """One asynchronous recorder event plus a consistent state snapshot."""

    type: RecordingEventType
    snapshot: RecordingSnapshot
    detail: str | None = None


@dataclass(frozen=True, slots=True)
class CapsSpec:
    """GStreamer caps represented without importing GStreamer."""

    media_type: str
    fields: tuple[tuple[str, str | int | bool], ...] = ()

    def to_string(self) -> str:
        """Return a deterministic string accepted by ``Gst.Caps``."""

        suffix = "".join(f",{key}={value}" for key, value in self.fields)
        return f"{self.media_type}{suffix}"


@dataclass(frozen=True, slots=True)
class ElementSpec:
    """One named factory and its safely assigned GObject properties."""

    factory: str
    name: str
    properties: tuple[tuple[str, object], ...] = ()


@dataclass(frozen=True, slots=True)
class RecordingPipelinePlan:
    """Immutable and offline-testable recording pipeline description."""

    output_path: Path
    format: RecordingFormat
    source_factory: str
    channels: int
    output_fd: int | None
    elements: tuple[ElementSpec, ...]
    links: tuple[tuple[str, str], ...]

    def element(self, name: str) -> ElementSpec:
        """Return a named element or raise ``KeyError``."""

        for element in self.elements:
            if element.name == name:
                return element
        raise KeyError(name)


@dataclass(slots=True)
class BuiltRecordingPipeline:
    """Concrete pipeline and named elements created from a plan."""

    pipeline: object
    elements: dict[str, object]


class SignalPlayer(Protocol):
    """Port used by :class:`Recorder` for non-recorded command cues."""

    def play(
        self,
        signal: RecordingSignal,
        callback: Callable[[bool, str | None], None],
    ) -> None:
        """Play one cue and invoke *callback* exactly once on completion."""

    def close(self) -> None:
        """Stop a current cue and release its resources."""


_SUPPORTED_SOURCES = ("pulsesrc", "autoaudiosrc")
_CAPTURE_RATE = 48_000
_PCM16_BYTES_PER_SAMPLE = 2
_RIFF_SIZE_FIELD_MAX = 0xFFFF_FFFF
_PCM16_WAV_RIFF_OVERHEAD_BYTES = 36
MAX_CLASSIC_RIFF_PCM_BYTES = (
    _RIFF_SIZE_FIELD_MAX - _PCM16_WAV_RIFF_OVERHEAD_BYTES
)


def _dispatch_on_main(callback: Callable[[], None]) -> None:
    """Run *callback* later on GLib's owning main context.

    A GStreamer pad probe runs on a streaming thread.  ``GLib.idle_add`` is
    thread-safe and, unlike calling :meth:`Recorder.stop` from the probe,
    cannot re-enter pipeline state changes while a buffer is being pushed.
    """

    from gi.repository import GLib

    def invoke() -> bool:
        callback()
        return GLib.SOURCE_REMOVE

    GLib.idle_add(invoke)


@dataclass(slots=True)
class _ClassicRiffPcmBudget:
    """Count PCM bytes admitted to one classic RIFF/WAVE muxer."""

    limit_bytes: int
    accepted_bytes: int = 0
    limit_reached: bool = False
    stop_scheduled: bool = False

    def accept(self, buffer_bytes: int) -> bool:
        if self.limit_reached:
            return False
        if buffer_bytes < 0 or buffer_bytes > self.limit_bytes - self.accepted_bytes:
            self.limit_reached = True
            return False
        self.accepted_bytes += buffer_bytes
        return True


@dataclass(frozen=True, slots=True)
class SignalSegment:
    """One tone or silence interval in a command cue.

    ``frequency_hz=None`` represents digital silence.  Volume is a normalized
    amplitude, not a desktop mixer setting.
    """

    frequency_hz: float | None
    duration_ms: int
    volume: float = 0.25


SIGNAL_SEQUENCE_PLANS: dict[RecordingSignal, tuple[SignalSegment, ...]] = {
    # The final silence is an acoustic-tail guard before capture-gate opening.
    RecordingSignal.START: (
        SignalSegment(440.0, 100),
        SignalSegment(580.0, 100),
        SignalSegment(None, 100, 0.0),
    ),
    RecordingSignal.RESUME: (
        SignalSegment(440.0, 100),
        SignalSegment(580.0, 100),
        SignalSegment(None, 100, 0.0),
    ),
    RecordingSignal.PAUSE: (
        SignalSegment(580.0, 100),
        SignalSegment(None, 60, 0.0),
        SignalSegment(580.0, 100),
    ),
    RecordingSignal.STOP: (
        SignalSegment(580.0, 100),
        SignalSegment(440.0, 100),
        SignalSegment(None, 60, 0.0),
        SignalSegment(440.0, 100),
    ),
}
"""Exact Android-compatible tone/silence plans, synthesized at runtime."""


def build_recording_plan(
    output_path: str | Path,
    settings: RecordingSettings,
    *,
    source_factory: str = "pulsesrc",
    channels: int | None = None,
    output_fd: int | None = None,
) -> RecordingPipelinePlan:
    """Describe one safe GStreamer capture pipeline.

    The path is assigned directly to ``filesink.location``; it is never
    interpolated into a GStreamer launch string.  The first element after the
    source is an exact raw-audio caps filter.  A stereo plan therefore asks the
    input device for two channels and cannot silently manufacture two equal
    channels with ``audioconvert``.

    ``source_factory`` is deliberately limited to ``pulsesrc`` and
    ``autoaudiosrc``.  :class:`Recorder` tries PulseAudio first (including the
    PipeWire Pulse compatibility server) and then the automatic desktop source.
    """

    if not isinstance(settings, RecordingSettings):
        raise TypeError("settings must be RecordingSettings")
    if source_factory not in _SUPPORTED_SOURCES:
        raise ValueError(f"unsupported source factory: {source_factory}")
    active_channels = settings.channels if channels is None else int(channels)
    if active_channels not in (1, 2):
        raise ValueError("channels must be exactly 1 or 2")
    if output_fd is not None and (isinstance(output_fd, bool) or output_fd < 0):
        raise ValueError("output_fd must be a non-negative file descriptor")
    path = Path(output_path).expanduser()
    if not str(output_path).strip() or path == Path("."):
        raise ValueError("output_path must name a file")

    source_properties: tuple[tuple[str, object], ...] = ()
    if source_factory == "pulsesrc":
        source_properties = (("do-timestamp", True),)

    input_caps = CapsSpec(
        "audio/x-raw",
        (
            ("format", "S16LE"),
            ("layout", "interleaved"),
            ("rate", _CAPTURE_RATE),
            ("channels", active_channels),
        ),
    )
    elements: list[ElementSpec] = [
        ElementSpec(source_factory, "audio-source", source_properties),
        ElementSpec("capsfilter", "input-caps", (("caps", input_caps),)),
        # The gate keeps every locally generated cue outside encoded audio.
        # ``forward-sticky-events`` is essential: Stop closes the data gate
        # before sending EOS, and muxers still need that EOS to finalize the
        # container.  The valve enum's stable integer value is used so the
        # dependency-free plan remains importable without PyGObject.
        ElementSpec(
            "valve",
            "capture-gate",
            (("drop", True), ("drop-mode", 1)),
        ),
        ElementSpec("audioconvert", "audio-convert"),
        ElementSpec("audioresample", "audio-resample"),
        ElementSpec("volume", "input-gain", (("volume", settings.linear_gain),)),
    ]

    if settings.format is RecordingFormat.OGG_OPUS:
        elements.extend(
            (
                ElementSpec(
                    "opusenc",
                    "audio-encoder",
                    (
                        ("bitrate", settings.bitrate_kbps * 1_000),
                        ("complexity", 10),
                    ),
                ),
                ElementSpec("oggmux", "container-muxer"),
            )
        )
    elif settings.format is RecordingFormat.MP3:
        elements.extend(
            (
                ElementSpec(
                    "lamemp3enc",
                    "audio-encoder",
                    (
                        ("target", 1),  # GstLameMP3EncTarget.BITRATE
                        ("bitrate", settings.bitrate_kbps),
                        ("cbr", True),
                        ("mono", active_channels == 1),
                    ),
                ),
                ElementSpec("mpegaudioparse", "audio-parser"),
            )
        )
    elif settings.format is RecordingFormat.WAV:
        pcm_caps = CapsSpec(
            "audio/x-raw",
            (
                ("format", "S16LE"),
                ("layout", "interleaved"),
                ("rate", _CAPTURE_RATE),
                ("channels", active_channels),
            ),
        )
        elements.extend(
            (
                ElementSpec("capsfilter", "pcm16-caps", (("caps", pcm_caps),)),
                ElementSpec("wavenc", "container-muxer"),
                # ``wavenc`` can also negotiate RF64.  MiniRec promises the
                # Android-compatible classic RIFF variant and enforces its
                # 32-bit length fields before this muxer.
                ElementSpec(
                    "capsfilter",
                    "classic-wav-caps",
                    (("caps", CapsSpec("audio/x-wav")),),
                ),
            )
        )
    else:  # pragma: no cover - RecordingSettings prevents unknown enum values.
        raise ValueError(f"unsupported format: {settings.format!r}")

    if output_fd is None:
        elements.append(
            ElementSpec(
                "filesink",
                "output-file",
                (
                    ("location", str(path)),
                    ("sync", False),
                ),
            )
        )
    else:
        # Recorder keeps this verified descriptor open through EOS and fsync.
        elements.append(
            ElementSpec(
                "fdsink",
                "output-file",
                (("fd", output_fd), ("sync", False)),
            )
        )
    links = tuple(
        (left.name, right.name) for left, right in zip(elements, elements[1:])
    )
    return RecordingPipelinePlan(
        output_path=path,
        format=settings.format,
        source_factory=source_factory,
        channels=active_channels,
        output_fd=output_fd,
        elements=tuple(elements),
        links=links,
    )


def build_gstreamer_pipeline(
    plan: RecordingPipelinePlan,
    gst: object,
) -> BuiltRecordingPipeline:
    """Instantiate *plan* with an injected ``Gst`` module.

    This function does no state changes and opens no microphone.  On failure it
    returns all already-created elements to ``NULL`` through the parent pipeline
    and raises :class:`PipelineBuildError`.
    """

    try:
        pipeline = gst.Pipeline.new("minirec-recorder")
    except Exception as error:  # pragma: no cover - defensive GI boundary.
        raise PipelineBuildError("GStreamer could not create a pipeline") from error
    if pipeline is None:
        raise PipelineBuildError("GStreamer could not create a pipeline")

    concrete: dict[str, object] = {}
    try:
        for spec in plan.elements:
            element = gst.ElementFactory.make(spec.factory, spec.name)
            if element is None:
                raise PipelineBuildError(
                    f"required GStreamer element is unavailable: {spec.factory}"
                )
            for property_name, value in spec.properties:
                if isinstance(value, CapsSpec):
                    value = gst.Caps.from_string(value.to_string())
                    if value is None:
                        raise PipelineBuildError(
                            f"GStreamer rejected caps for {spec.name}"
                        )
                element.set_property(property_name, value)
            added = pipeline.add(element)
            if added is False:
                raise PipelineBuildError(f"could not add {spec.factory} to pipeline")
            concrete[spec.name] = element

        for left_name, right_name in plan.links:
            if not concrete[left_name].link(concrete[right_name]):
                raise PipelineBuildError(
                    f"could not link {left_name} to {right_name}"
                )
    except PipelineBuildError:
        _set_null_safely(pipeline, gst)
        raise
    except Exception as error:
        _set_null_safely(pipeline, gst)
        raise PipelineBuildError(f"could not configure recording pipeline: {error}") from error
    return BuiltRecordingPipeline(pipeline=pipeline, elements=concrete)


class GStreamerSignalPlayer:
    """Synthesize short command cues through a separate audio pipeline.

    Exact Android-compatible multi-tone PCM is pushed through ``appsrc``.  No
    bundled media file or GTK component is required.  Starting a new cue
    cancels the previous cue; its obsolete completion callback is intentionally
    not invoked.
    """

    def __init__(self, *, gst: object | None = None) -> None:
        self._gst = _load_gst() if gst is None else gst
        self._pipeline: object | None = None
        self._bus: object | None = None
        self._bus_handler: object | None = None
        self._callback: Callable[[bool, str | None], None] | None = None
        self._closed = False

    def play(
        self,
        signal: RecordingSignal,
        callback: Callable[[bool, str | None], None],
    ) -> None:
        """Play *signal* asynchronously and report EOS or an error."""

        if self._closed:
            raise RecordingError("signal player is closed")
        if not isinstance(signal, RecordingSignal):
            raise TypeError("signal must be RecordingSignal")
        self._dispose()
        pcm = synthesize_signal_pcm(signal)

        gst = self._gst
        pipeline = gst.Pipeline.new("minirec-command-signal")
        if pipeline is None:
            raise RecordingUnavailableError("could not create command-signal pipeline")
        specs = (
            ElementSpec(
                "appsrc",
                "signal-source",
                (
                    ("caps", CapsSpec(
                        "audio/x-raw",
                        (
                            ("format", "S16LE"),
                            ("layout", "interleaved"),
                            ("rate", _CAPTURE_RATE),
                            ("channels", 1),
                        ),
                    )),
                    ("format", gst.Format.TIME),
                    ("block", True),
                ),
            ),
            ElementSpec("audioconvert", "signal-convert"),
            ElementSpec("audioresample", "signal-resample"),
            ElementSpec("autoaudiosink", "signal-output"),
        )
        elements: list[object] = []
        try:
            for spec in specs:
                element = gst.ElementFactory.make(spec.factory, spec.name)
                if element is None:
                    raise PipelineBuildError(
                        f"command-signal element is unavailable: {spec.factory}"
                    )
                for property_name, value in spec.properties:
                    if isinstance(value, CapsSpec):
                        value = gst.Caps.from_string(value.to_string())
                    element.set_property(property_name, value)
                pipeline.add(element)
                elements.append(element)
            for left, right in zip(elements, elements[1:]):
                if not left.link(right):
                    raise PipelineBuildError("could not link command-signal pipeline")

            bus = pipeline.get_bus()
            if bus is None:
                raise PipelineBuildError("command-signal pipeline has no bus")
            bus.add_signal_watch()
            self._pipeline = pipeline
            self._bus = bus
            self._callback = callback
            self._bus_handler = bus.connect("message", self._on_message)
            result = pipeline.set_state(gst.State.PLAYING)
            if result == gst.StateChangeReturn.FAILURE:
                raise RecordingError("could not start command signal")
            buffer = gst.Buffer.new_allocate(None, len(pcm), None)
            if buffer is None or buffer.fill(0, pcm) != len(pcm):
                raise RecordingError("could not allocate command-signal PCM")
            buffer.pts = 0
            buffer.dts = 0
            buffer.duration = round(
                len(pcm) / 2 / _CAPTURE_RATE * gst.SECOND
            )
            flow_result = elements[0].emit("push-buffer", buffer)
            if flow_result != gst.FlowReturn.OK:
                raise RecordingError("could not queue command-signal PCM")
            eos_result = elements[0].emit("end-of-stream")
            if eos_result != gst.FlowReturn.OK:
                raise RecordingError("could not finish command-signal PCM")
        except Exception:
            _set_null_safely(pipeline, gst)
            self._dispose()
            raise

    def close(self) -> None:
        """Release a cue pipeline; calling repeatedly is safe."""

        if self._closed:
            return
        self._closed = True
        self._dispose()

    def _on_message(self, _bus: object, message: object) -> None:
        if self._closed:
            return
        if message.type == self._gst.MessageType.EOS:
            self._finish(True, None)
        elif message.type == self._gst.MessageType.ERROR:
            error, _debug = message.parse_error()
            self._finish(False, str(error).strip() or "command signal failed")

    def _finish(self, success: bool, detail: str | None) -> None:
        callback = self._callback
        self._callback = None
        self._dispose()
        if callback is not None:
            callback(success, detail)

    def _dispose(self) -> None:
        pipeline = self._pipeline
        bus = self._bus
        handler = self._bus_handler
        self._pipeline = None
        self._bus = None
        self._bus_handler = None
        self._callback = None
        if pipeline is not None:
            _set_null_safely(pipeline, self._gst)
        if bus is not None:
            if handler is not None:
                try:
                    bus.disconnect(handler)
                except (AttributeError, TypeError, ValueError):
                    pass
            try:
                bus.remove_signal_watch()
            except (AttributeError, TypeError, ValueError):
                pass


def synthesize_signal_pcm(
    signal: RecordingSignal,
    *,
    sample_rate: int = _CAPTURE_RATE,
) -> bytes:
    """Return mono signed-16 PCM for an exact MiniRec command sequence.

    Tone phase starts at zero for each Android source-asset equivalent.  The
    amplitude is 25 percent (within the measured 22--27.5 percent range), and
    silence/tail intervals contain literal zero samples.  This pure function is
    deterministic and can be verified without GStreamer or an audio device.
    """

    if not isinstance(signal, RecordingSignal):
        raise TypeError("signal must be RecordingSignal")
    if isinstance(sample_rate, bool) or not isinstance(sample_rate, int):
        raise TypeError("sample_rate must be an integer")
    if sample_rate <= 0:
        raise ValueError("sample_rate must be positive")
    samples = array("h")
    for segment in SIGNAL_SEQUENCE_PLANS[signal]:
        sample_count = round(sample_rate * segment.duration_ms / 1_000)
        if segment.frequency_hz is None:
            samples.extend([0] * sample_count)
            continue
        scale = 32_767 * segment.volume
        angular_step = 2.0 * math.pi * segment.frequency_hz / sample_rate
        samples.extend(
            round(scale * math.sin(angular_step * index))
            for index in range(sample_count)
        )
    if sys.byteorder != "little":  # Gst caps explicitly request S16LE.
        samples.byteswap()
    return samples.tobytes()


class Recorder:
    """Own one asynchronous GStreamer recording session.

    Parameters are dependency-injected for deterministic tests.  With defaults,
    PyGObject is imported lazily and events are delivered from the GLib main
    context which dispatches GStreamer's bus signal watch.

    ``start`` never overwrites an existing path.  Stereo attempts are ordered as
    ``pulsesrc``, ``autoaudiosrc``, followed by the same sources in mono when
    ``allow_mono_fallback`` is true.  The exact two-channel caps sit immediately
    after each source.  An asynchronous startup error advances to the next
    candidate; errors after capture has started are reported and never silently
    change the current file's channel layout.

    ``start(..., prepared=True)`` safely adopts an already-created empty regular
    pending file without following symlinks.  Otherwise it creates a private
    file atomically.  In both cases a verified descriptor is passed to
    ``fdsink``, retained through EOS, synchronized, and closed before the Stop
    signal begins.

    ``close`` is safe during capture: it first performs an EOS stop and becomes
    ``CLOSED`` only after both mux finalization and the Stop signal complete.
    """

    def __init__(
        self,
        settings: RecordingSettings = RecordingSettings(),
        on_event: Callable[[RecordingEvent], None] | None = None,
        *,
        gst: object | None = None,
        clock: Callable[[], float] = time.monotonic,
        signal_player: SignalPlayer | None = None,
        pipeline_builder: Callable[
            [RecordingPipelinePlan, object], BuiltRecordingPipeline
        ] = build_gstreamer_pipeline,
        source_factories: Iterable[str] = _SUPPORTED_SOURCES,
        allow_mono_fallback: bool = True,
        dispatcher: Callable[[Callable[[], None]], None] = _dispatch_on_main,
        wav_data_limit_bytes: int = MAX_CLASSIC_RIFF_PCM_BYTES,
    ) -> None:
        if not isinstance(settings, RecordingSettings):
            raise TypeError("settings must be RecordingSettings")
        sources = tuple(source_factories)
        if not sources or any(source not in _SUPPORTED_SOURCES for source in sources):
            raise ValueError("source_factories may contain pulsesrc and autoaudiosrc")
        if not callable(dispatcher):
            raise TypeError("dispatcher must be callable")
        if (
            type(wav_data_limit_bytes) is not int
            or not 0 <= wav_data_limit_bytes <= MAX_CLASSIC_RIFF_PCM_BYTES
        ):
            raise ValueError(
                "wav_data_limit_bytes must be between zero and the classic RIFF limit"
            )
        self.settings = settings
        self._on_event = on_event or _ignore_recording_event
        self._gst = _load_gst() if gst is None else gst
        self._clock = clock
        self._signal_player = (
            GStreamerSignalPlayer(gst=self._gst)
            if signal_player is None
            else signal_player
        )
        self._pipeline_builder = pipeline_builder
        self._source_factories = sources
        self._allow_mono_fallback = bool(allow_mono_fallback)
        self._dispatcher = dispatcher
        self._wav_data_limit_bytes = wav_data_limit_bytes

        self._phase = RecordingPhase.IDLE
        self._output_path: Path | None = None
        self._output_fd: int | None = None
        self._error: str | None = None
        self._active_plan: RecordingPipelinePlan | None = None
        self._built: BuiltRecordingPipeline | None = None
        self._bus: object | None = None
        self._bus_handler: object | None = None
        self._wav_probe_pad: object | None = None
        self._wav_probe_id: object | None = None
        self._wav_budget: _ClassicRiffPcmBudget | None = None
        self._candidates: list[tuple[str, int]] = []
        self._candidate_index = 0
        self._elapsed_before_active = 0.0
        self._active_since: float | None = None
        self._pipeline_paused = False
        self._start_signal_started = False
        self._start_cue_done = False
        self._startup_pipeline_ready = False
        self._startup_gate_open = False
        self._eos_seen = False
        self._stop_signal_done = False
        self._close_after_stop = False
        self._signal_token = 0

    @property
    def phase(self) -> RecordingPhase:
        """Return the current lifecycle phase."""

        return self._phase

    @property
    def active_plan(self) -> RecordingPipelinePlan | None:
        """Return the selected pipeline description, if any."""

        return self._active_plan

    @property
    def elapsed_seconds(self) -> float:
        """Return captured time, excluding all paused and cue intervals."""

        elapsed = self._elapsed_before_active
        if self._active_since is not None:
            elapsed += max(0.0, self._clock() - self._active_since)
        return max(0.0, elapsed)

    @property
    def snapshot(self) -> RecordingSnapshot:
        """Return an immutable state snapshot suitable for UI rendering."""

        plan = self._active_plan
        return RecordingSnapshot(
            phase=self._phase,
            output_path=self._output_path,
            elapsed_seconds=self.elapsed_seconds,
            requested_channels=self.settings.channels,
            active_channels=plan.channels if plan else None,
            source_factory=plan.source_factory if plan else None,
            error=self._error,
        )

    def set_event_callback(self, callback: Callable[[RecordingEvent], None]) -> None:
        """Replace the callback used for future asynchronous events."""

        self._on_event = callback

    def start(self, output_path: str | Path, *, prepared: bool = False) -> bool:
        """Begin asynchronous capture and play the Start signal.

        Returns ``False`` if the recorder is busy or closed.  Invalid paths,
        especially an existing output, raise before GStreamer is touched.
        Successful return means a candidate pipeline accepted ``PLAYING``;
        ``RECORDING`` is reported after the separately synthesized cue ends.
        """

        if self._phase not in {
            RecordingPhase.IDLE,
            RecordingPhase.STOPPED,
            RecordingPhase.ERROR,
        }:
            return False
        path = Path(output_path).expanduser()
        if not path.parent.is_dir():
            raise FileNotFoundError(f"recording directory does not exist: {path.parent}")
        if path.name in {"", ".", ".."}:
            raise ValueError("output_path must name a file")

        self._teardown_pipeline()
        self._release_output_fd(sync=False)
        self._output_fd = _open_recording_output(path, prepared=prepared)
        self._output_path = path
        self._error = None
        self._active_plan = None
        self._elapsed_before_active = 0.0
        self._active_since = None
        self._pipeline_paused = False
        self._start_signal_started = False
        self._start_cue_done = False
        self._startup_pipeline_ready = False
        self._startup_gate_open = False
        self._eos_seen = False
        self._stop_signal_done = False
        self._close_after_stop = False
        self._signal_token += 1
        self._candidates = self._make_candidates()
        self._candidate_index = 0
        self._set_phase(RecordingPhase.STARTING)
        return self._activate_next_candidate()

    def pause(self) -> bool:
        """Stop counting/capturing immediately, then play the Pause signal."""

        if self._phase is not RecordingPhase.RECORDING:
            return False
        if not self._close_gate():
            return False
        self._freeze_elapsed()
        self._set_phase(RecordingPhase.PAUSING)

        def finish_pause() -> None:
            if self._phase is not RecordingPhase.PAUSING:
                return
            if not self._set_pipeline_state(self._gst.State.PAUSED, "pause recording"):
                return
            self._pipeline_paused = True
            self._set_phase(RecordingPhase.PAUSED)

        self._play_signal(RecordingSignal.PAUSE, finish_pause)
        return True

    def resume(self) -> bool:
        """Play the Resume signal while paused, then continue capture."""

        if self._phase is not RecordingPhase.PAUSED:
            return False
        self._set_phase(RecordingPhase.RESUMING)

        def finish_resume() -> None:
            if self._phase is not RecordingPhase.RESUMING:
                return
            if not self._set_pipeline_state(self._gst.State.PLAYING, "resume recording"):
                return
            self._pipeline_paused = False
            if not self._open_gate():
                return
            self._active_since = self._clock()
            self._set_phase(RecordingPhase.RECORDING)

        self._play_signal(RecordingSignal.RESUME, finish_resume)
        return True

    def stop(self) -> bool:
        """Finalize through EOS while playing an unrecorded Stop signal."""

        active_phases = {
            RecordingPhase.STARTING,
            RecordingPhase.RECORDING,
            RecordingPhase.PAUSING,
            RecordingPhase.PAUSED,
            RecordingPhase.RESUMING,
        }
        if self._phase is RecordingPhase.STOPPING:
            return True
        if self._phase not in active_phases or self._built is None:
            return False
        self._signal_token += 1  # invalidate an in-flight command cue callback
        if not self._close_gate():
            return False
        self._freeze_elapsed()
        self._set_phase(RecordingPhase.STOPPING)
        self._eos_seen = False
        self._stop_signal_done = False

        if self._pipeline_paused:
            if not self._set_pipeline_state(
                self._gst.State.PLAYING,
                "wake the pipeline for finalization",
            ):
                return False
            self._pipeline_paused = False
        try:
            accepted = self._built.pipeline.send_event(self._gst.Event.new_eos())
        except Exception as error:
            self._fail(f"could not send recording EOS: {error}")
            return False
        if accepted is False:
            self._fail("GStreamer rejected recording EOS")
            return False

        return True

    def timeout_stalled_stop(self) -> bool:
        """Fail a Stop whose accepted EOS never reached the muxer.

        The synchronized pending file is deliberately retained.  The storage
        journal can then publish only a format-verified safe prefix instead of
        either hanging forever or guessing that the container was finalized.
        A controller calls this from an injectable/monotonic watchdog.
        """

        if self._phase is not RecordingPhase.STOPPING:
            return False
        self._fail("timed out while waiting for recording finalization")
        return True

    def emergency_close_for_process_exit(self) -> None:
        """Synchronously stop all I/O while retaining recovery state.

        Normal UI close always goes through EOS.  This path is reserved for an
        externally forced GApplication shutdown where the main loop cannot be
        trusted to deliver a future EOS message.  It closes the data gate,
        brings the pipeline to NULL, synchronizes the descriptor and leaves
        publication to the already-persisted storage journal on next startup.
        """

        if self._phase is RecordingPhase.CLOSED:
            return
        self._signal_token += 1
        self._freeze_elapsed()
        if self._built is not None:
            try:
                self._built.elements["capture-gate"].set_property("drop", True)
            except Exception:
                pass
        self._teardown_pipeline()
        try:
            self._release_output_fd(sync=self._output_fd is not None)
        except OSError:
            pass
        try:
            self._signal_player.close()
        finally:
            self._set_phase(RecordingPhase.CLOSED)

    def close(self) -> None:
        """EOS-finalize active capture, or synchronously release an idle one."""

        if self._phase is RecordingPhase.CLOSED:
            return
        if self._phase is RecordingPhase.STOPPING:
            self._close_after_stop = True
            return
        if self._phase in {
            RecordingPhase.STARTING,
            RecordingPhase.RECORDING,
            RecordingPhase.PAUSING,
            RecordingPhase.PAUSED,
            RecordingPhase.RESUMING,
        }:
            self._close_after_stop = True
            if not self.stop() and self._phase is not RecordingPhase.ERROR:
                self._fail("could not finalize recording while closing")
            return
        self._close_now()

    def _make_candidates(self) -> list[tuple[str, int]]:
        requested = self.settings.channels
        candidates = [(source, requested) for source in self._source_factories]
        if requested == 2 and self._allow_mono_fallback:
            candidates.extend((source, 1) for source in self._source_factories)
        return candidates

    def _activate_next_candidate(self, previous_error: str | None = None) -> bool:
        self._teardown_pipeline()
        # A failed startup candidate may have received buffers after the Start
        # cue.  Its output is discarded below, so its provisional elapsed time
        # must be discarded too.  The one user-facing cue, however, keeps
        # playing across candidate negotiation and is never duplicated.
        self._active_since = None
        self._elapsed_before_active = 0.0
        self._startup_pipeline_ready = False
        self._startup_gate_open = False
        path = self._output_path
        if path is None:
            self._fail("recording output path is missing")
            return False

        failures: list[str] = []
        if previous_error:
            failures.append(previous_error)
        while self._candidate_index < len(self._candidates):
            source, channels = self._candidates[self._candidate_index]
            self._candidate_index += 1
            try:
                self._reset_output_for_candidate()
            except OSError as error:
                self._fail(f"could not reset pending recording: {error}")
                return False
            plan = build_recording_plan(
                path,
                self.settings,
                source_factory=source,
                channels=channels,
                output_fd=self._output_fd,
            )
            try:
                built = self._pipeline_builder(plan, self._gst)
                bus = built.pipeline.get_bus()
                if bus is None:
                    raise PipelineBuildError("recording pipeline has no message bus")
                bus.add_signal_watch()
                handler = bus.connect("message", self._on_bus_message)
                self._active_plan = plan
                self._built = built
                self._bus = bus
                self._bus_handler = handler
                self._install_wav_limit_probe(plan, built)
                if not self._close_gate():
                    return False
                result = built.pipeline.set_state(self._gst.State.PLAYING)
                if result == self._gst.StateChangeReturn.FAILURE:
                    raise RecordingError("GStreamer rejected PLAYING")
                self._startup_pipeline_ready = result in {
                    self._gst.StateChangeReturn.SUCCESS,
                    self._gst.StateChangeReturn.NO_PREROLL,
                }
            except Exception as error:
                failures.append(f"{source}/{channels}ch: {error}")
                self._teardown_pipeline()
                continue

            if source != self._source_factories[0]:
                self._emit(
                    RecordingEventType.SOURCE_FALLBACK,
                    f"using {source} after {self._source_factories[0]}",
                )
            if channels != self.settings.channels:
                self._emit(
                    RecordingEventType.CHANNEL_FALLBACK,
                    "stereo input unavailable; recording clean mono",
                )

            if not self._start_signal_started:
                self._start_signal_started = True
                self._play_signal(RecordingSignal.START, self._finish_start_cue)
            elif self._start_cue_done:
                self._open_startup_gate()
            self._maybe_finish_startup()
            return True

        detail = "; ".join(failures) or "no recording source is available"
        self._fail(detail)
        return False

    def _on_bus_message(self, _bus: object, message: object) -> None:
        if self._phase in {RecordingPhase.CLOSED, RecordingPhase.ERROR}:
            return
        if message.type == self._gst.MessageType.EOS:
            if self._phase is RecordingPhase.STOPPING:
                self._eos_seen = True
                self._finish_eos_then_play_stop()
            else:
                self._fail("recording ended unexpectedly")
        elif message.type == self._gst.MessageType.ERROR:
            error, debug = message.parse_error()
            detail = str(error).strip() or "GStreamer recording failed"
            if debug:
                detail = f"{detail} ({debug})"
            if self._phase is RecordingPhase.STARTING:
                self._activate_next_candidate(detail)
            else:
                self._fail(detail)
        elif (
            message.type == self._gst.MessageType.ASYNC_DONE
            and self._phase is RecordingPhase.STARTING
            and self._built is not None
            and getattr(message, "src", None) is self._built.pipeline
        ):
            self._startup_pipeline_ready = True
            self._maybe_finish_startup()
        elif (
            message.type == self._gst.MessageType.STATE_CHANGED
            and self._phase is RecordingPhase.STARTING
            and self._built is not None
            and getattr(message, "src", None) is self._built.pipeline
        ):
            try:
                _old, current, _pending = message.parse_state_changed()
            except Exception:
                return
            if current == self._gst.State.PLAYING:
                self._startup_pipeline_ready = True
                self._maybe_finish_startup()

    def _install_wav_limit_probe(
        self,
        plan: RecordingPipelinePlan,
        built: BuiltRecordingPipeline,
    ) -> None:
        """Drop the first PCM buffer which cannot fit classic RIFF.

        The probe is immediately upstream of ``wavenc``.  Returning ``DROP``
        is the exact admission boundary: no byte from an over-limit buffer can
        reach either of WAV's unsigned 32-bit length fields.
        """

        self._clear_wav_limit_probe()
        if plan.format is not RecordingFormat.WAV:
            return
        block_align = _PCM16_BYTES_PER_SAMPLE * plan.channels
        aligned_limit = self._wav_data_limit_bytes - (
            self._wav_data_limit_bytes % block_align
        )
        budget = _ClassicRiffPcmBudget(aligned_limit)
        try:
            pad = built.elements["pcm16-caps"].get_static_pad("src")
        except Exception as error:
            raise PipelineBuildError(
                "could not access the WAV PCM admission pad"
            ) from error
        if pad is None:
            raise PipelineBuildError("WAV PCM admission pad is unavailable")

        def inspect_buffer(_pad: object, info: object) -> object:
            return self._inspect_wav_buffer(info, budget, built)

        try:
            probe_id = pad.add_probe(
                self._gst.PadProbeType.BUFFER,
                inspect_buffer,
            )
        except Exception as error:
            raise PipelineBuildError(
                "could not install the WAV size guard"
            ) from error
        if not probe_id:
            raise PipelineBuildError("could not install the WAV size guard")
        self._wav_probe_pad = pad
        self._wav_probe_id = probe_id
        self._wav_budget = budget

    def _inspect_wav_buffer(
        self,
        info: object,
        budget: _ClassicRiffPcmBudget,
        built: BuiltRecordingPipeline,
    ) -> object:
        """Inspect one raw PCM buffer on GStreamer's streaming thread."""

        if self._wav_budget is not budget:
            return self._gst.PadProbeReturn.DROP
        try:
            buffer = info.get_buffer()
            buffer_bytes = int(buffer.get_size()) if buffer is not None else 0
        except Exception:
            # An unmeasurable buffer cannot safely be admitted to a bounded
            # classic container.  Treat it exactly like an over-limit buffer.
            buffer_bytes = budget.limit_bytes + 1
        if budget.accept(buffer_bytes):
            return self._gst.PadProbeReturn.OK

        # Stop new data at both boundaries.  The probe drops this buffer and
        # every later one even if changing the upstream valve property fails.
        try:
            built.elements["capture-gate"].set_property("drop", True)
        except Exception:
            pass
        if not budget.stop_scheduled:
            budget.stop_scheduled = True
            try:
                self._dispatcher(lambda: self._stop_for_wav_limit(budget))
            except Exception:
                # Never mutate pipeline state reentrantly from this streaming
                # callback.  A later dropped buffer may retry dispatching.
                budget.stop_scheduled = False
        return self._gst.PadProbeReturn.DROP

    def _stop_for_wav_limit(self, budget: _ClassicRiffPcmBudget) -> None:
        """Enter the ordinary EOS state machine from the main context."""

        if self._wav_budget is not budget:
            return
        if self._phase is RecordingPhase.STOPPING:
            return
        if not self.stop() and self._phase not in {
            RecordingPhase.ERROR,
            RecordingPhase.STOPPED,
            RecordingPhase.CLOSED,
        }:
            self._fail("could not finalize WAV at the classic RIFF limit")

    def _clear_wav_limit_probe(self) -> None:
        pad = self._wav_probe_pad
        probe_id = self._wav_probe_id
        self._wav_probe_pad = None
        self._wav_probe_id = None
        self._wav_budget = None
        if pad is not None and probe_id is not None:
            try:
                pad.remove_probe(probe_id)
            except (AttributeError, TypeError, ValueError):
                pass

    def _finish_start_cue(self) -> None:
        """Open the data gate after the cue, then await pipeline readiness."""

        if self._phase is not RecordingPhase.STARTING:
            return
        self._start_cue_done = True
        self._open_startup_gate()
        self._maybe_finish_startup()

    def _open_startup_gate(self) -> None:
        if (
            self._phase is not RecordingPhase.STARTING
            or self._startup_gate_open
            or self._built is None
        ):
            return
        if not self._open_gate():
            return
        self._startup_gate_open = True
        self._active_since = self._clock()

    def _maybe_finish_startup(self) -> None:
        if (
            self._phase is RecordingPhase.STARTING
            and self._start_cue_done
            and self._startup_gate_open
            and self._startup_pipeline_ready
        ):
            self._set_phase(RecordingPhase.RECORDING)

    def _play_signal(
        self,
        signal: RecordingSignal,
        on_finished: Callable[[], None],
    ) -> None:
        self._signal_token += 1
        token = self._signal_token

        def completed(success: bool, detail: str | None) -> None:
            if token != self._signal_token:
                return
            if not success:
                self._emit(
                    RecordingEventType.SIGNAL_ERROR,
                    detail or f"{signal.name.casefold()} signal failed",
                )
            on_finished()

        try:
            self._signal_player.play(signal, completed)
        except Exception as error:
            self._emit(RecordingEventType.SIGNAL_ERROR, str(error))
            completed(True, None)

    def _finish_eos_then_play_stop(self) -> None:
        if not self._eos_seen or self._phase is not RecordingPhase.STOPPING:
            return
        self._teardown_pipeline()
        try:
            self._release_output_fd(sync=True)
        except OSError as error:
            self._fail(f"could not synchronize finalized recording: {error}")
            return

        def finish_stop_signal() -> None:
            if self._phase is not RecordingPhase.STOPPING:
                return
            self._stop_signal_done = True
            self._set_phase(RecordingPhase.STOPPED)
            self._emit(RecordingEventType.FINALIZED)
            if self._close_after_stop:
                self._close_now()

        # Android contract: the Stop cue starts only after EOS, NULL and fsync.
        self._play_signal(RecordingSignal.STOP, finish_stop_signal)

    def _close_gate(self) -> bool:
        if self._built is None:
            return False
        try:
            self._built.elements["capture-gate"].set_property("drop", True)
        except Exception as error:
            self._fail(f"could not close capture gate: {error}")
            return False
        return True

    def _open_gate(self) -> bool:
        if self._built is None:
            return False
        try:
            self._built.elements["capture-gate"].set_property("drop", False)
        except Exception as error:
            self._fail(f"could not open capture gate: {error}")
            return False
        return True

    def _freeze_elapsed(self) -> None:
        if self._active_since is None:
            return
        self._elapsed_before_active += max(0.0, self._clock() - self._active_since)
        self._active_since = None

    def _set_pipeline_state(self, state: object, operation: str) -> bool:
        if self._built is None:
            self._fail("recording pipeline is missing")
            return False
        try:
            result = self._built.pipeline.set_state(state)
        except Exception as error:
            self._fail(f"could not {operation}: {error}")
            return False
        if result == self._gst.StateChangeReturn.FAILURE:
            self._fail(f"GStreamer could not {operation}")
            return False
        return True

    def _teardown_pipeline(self) -> None:
        built = self._built
        bus = self._bus
        handler = self._bus_handler
        self._clear_wav_limit_probe()
        self._built = None
        self._bus = None
        self._bus_handler = None
        if built is not None:
            _set_null_safely(built.pipeline, self._gst)
        if bus is not None:
            if handler is not None:
                try:
                    bus.disconnect(handler)
                except (AttributeError, TypeError, ValueError):
                    pass
            try:
                bus.remove_signal_watch()
            except (AttributeError, TypeError, ValueError):
                pass

    def _fail(self, detail: str) -> None:
        if self._phase is RecordingPhase.CLOSED:
            return
        self._freeze_elapsed()
        self._error = detail
        self._signal_token += 1
        self._teardown_pipeline()
        try:
            self._release_output_fd(sync=True)
        except OSError:
            pass
        self._set_phase(RecordingPhase.ERROR)
        self._emit(RecordingEventType.ERROR, detail)
        if self._close_after_stop:
            self._close_now()

    def _close_now(self) -> None:
        self._signal_token += 1
        self._freeze_elapsed()
        self._teardown_pipeline()
        try:
            self._release_output_fd(sync=self._output_fd is not None)
        except OSError:
            pass
        try:
            self._signal_player.close()
        finally:
            self._set_phase(RecordingPhase.CLOSED)

    def _release_output_fd(self, *, sync: bool) -> None:
        descriptor = self._output_fd
        self._output_fd = None
        if descriptor is None:
            return
        try:
            if sync:
                os.fsync(descriptor)
        finally:
            os.close(descriptor)

    def _reset_output_for_candidate(self) -> None:
        descriptor = self._output_fd
        if descriptor is None:
            raise OSError("pending recording descriptor is closed")
        os.ftruncate(descriptor, 0)
        os.lseek(descriptor, 0, os.SEEK_SET)

    def _set_phase(self, phase: RecordingPhase) -> None:
        self._phase = phase
        self._emit(RecordingEventType.STATE_CHANGED)

    def _emit(self, event_type: RecordingEventType, detail: str | None = None) -> None:
        event = RecordingEvent(event_type, self.snapshot, detail)
        try:
            self._on_event(event)
        except Exception:
            # Presentation callbacks must never corrupt an audio session.
            pass


def _load_gst() -> object:
    try:
        import gi

        gi.require_version("Gst", "1.0")
        from gi.repository import Gst
    except (ImportError, ValueError) as error:
        raise RecordingUnavailableError(
            "GStreamer 1.0 Python bindings are unavailable"
        ) from error
    Gst.init(None)
    return Gst


def _open_recording_output(path: Path, *, prepared: bool) -> int:
    """Atomically create or safely adopt one private pending output.

    Adopting never follows a symlink and verifies that the object seen by
    ``lstat`` is the same empty regular file referenced by the open descriptor.
    The descriptor is intentionally returned open for use by ``fdsink``.
    """

    if not isinstance(prepared, bool):
        raise TypeError("prepared must be a boolean")
    common_flags = os.O_WRONLY | getattr(os, "O_CLOEXEC", 0)
    no_follow = getattr(os, "O_NOFOLLOW", 0)
    if not prepared:
        return os.open(
            path,
            common_flags | no_follow | os.O_CREAT | os.O_EXCL,
            0o600,
        )

    before = os.lstat(path)
    if not stat.S_ISREG(before.st_mode):
        raise ValueError("prepared recording must be a regular file")
    if before.st_size != 0:
        raise FileExistsError("prepared recording must be empty")
    descriptor = os.open(path, common_flags | no_follow)
    try:
        opened = os.fstat(descriptor)
        if not stat.S_ISREG(opened.st_mode):
            raise ValueError("prepared recording must be a regular file")
        if (opened.st_dev, opened.st_ino) != (before.st_dev, before.st_ino):
            raise RecordingError("prepared recording changed while being opened")
        if opened.st_size != 0:
            raise FileExistsError("prepared recording must be empty")
        return descriptor
    except Exception:
        os.close(descriptor)
        raise


def _set_null_safely(pipeline: object, gst: object) -> None:
    try:
        pipeline.set_state(gst.State.NULL)
    except Exception:
        pass


def _ignore_recording_event(_event: RecordingEvent) -> None:
    return
